### ISSUE TITLE
killed by SIGKIL

### ISSUE THREAD

**Issue by gulfemd** [bioinformatics-centre/BayesTyper#2]
Hi,

I keep getting this error when trying BayesTyper with the following options:

```
./bayesTyper -o integrated_calls -c chr20 -s samples.tsv -v /genotyping/vcf-files/test_bayes.vcf -g /genotyping/ref/hs38DHp.fa
```

Last few lines of the output:

```
[11/09/2017 19:24:58] Parsed 1200 alternative alleles and excluded:

	- Alleles on chromosome(s) not in genome: 0
	- Alleles with reference not equal to genome sequence: 0
	- Alleles with non-canonical bases (not ACGTN): 0
	- Alleles within 55 bases of chromosome end: 0
	- Alleles longer than 3000000 bases: 0

[11/09/2017 19:24:58] Out of 1200 variants:

	- Single nucleotides polymorphism: 0
	- Insertion: 102
	- Deletion: 170
	- Complex: 928
	- Mixture: 0
	- Unsupported (excluded): 0

[11/09/2017 19:24:58] Merged variants into 1200 clusters and further into 1198 groups

[11/09/2017 19:24:58] Shuffling intercluster regions ...
[11/09/2017 19:24:58] Finished shuffling

[11/09/2017 19:24:58] Sorting variant clusters by decreasing complexity (number of variants) ...
[11/09/2017 19:24:58] Finished sorting


[11/09/2017 19:24:58] Maximum resident set size: 3.20937 Gb

[11/09/2017 19:24:58] Counting smallmers ...
Killed
```

samples.tsv:

```
sample_1	M	/data/ERR1955396
```
with 36 GB kmc_suf size and 33.6 MB kmc_pre size (gathered using `kmc_tools union` since the data is paired).

Could you help me find out the cause?

**Comment by jonassibbesen** [comment]
Hi,

Thanks for letting us know about the issue. Unfortunately, I do not on top of my head know what the issue is.

How much memory do you have available? The step were it terminates uses ~9Gb of memory independent of the input size.  

If it is not a memory problem, it would help a lot, to figure what the issue is, if I had access to the data you are running on. Would it be possible for you to share the data using e.g. ftp or Dropbox? I only need the vcf file and genome (k-mer counts are used after the error occurs). You can send me a link to the data on this mail: jasi@binf.ku.dk

Best wishes,

Jonas

**Comment by gulfemd** [comment]
Hi Jonas,

I just sent the email, but in the meanwhile, it would be great if you can send some sample inputs so that I can debug too.

Thanks a lot,
Gulfem

**Comment by jonassibbesen** [comment]
Hi Gulfem,

Thanks for the data. You can find a test dataset here:

http://people.binf.ku.dk/%7Elassemaretty/bayesTyper/bt_example_chr22.tar.gz

Try to run the following pipeline on the dataset:

`kmc -k55 @reads_chr22.txt kmers_chr22 .`
`bayesTyperTools combine -v CEU:variants_ceu_chr22.vcf,PP:variants_pp_chr22.vcf -o variants_chr22`
`bayesTyper -v variants_chr22.vcf -s sample.txt -g chr22.fa -d decoy.fa -p <num_threads>`

Remember to specify the number of threads for BayesTyper (`<num_threads>`). I used 24 threads and it took ~7 minutes to run the whole pipeline on my server. Also BayesTyper used a bit over 12Gb of memory.
 
I also tried to run BayesTyper on the data you sent me and did not have the same problem with the _Counting smallmers_ step. However the program crashed later in the code, due to insufficient number input variants for parameter estimation (BayesTyper was build to run on millions of variants).

Finally, I can see from your log file that you are using the pre-compiled binary version for Linux. If you also have problems on the test dataset, try to clone and compile from scratch instead. It might be a problem with the pre-compiled version.

Best wishes,

Jonas

**Comment by gulfemd** [comment]
Hi Jonas,

Thanks for all the information! I managed to run it on a different machine with a different vcf file, probably it was a memory issue.

Best wishes,
Gulfem
